### ISSUE TITLE
Propose package manager to be used as default (yarn vs. npm)

### ISSUE THREAD

**Issue by jschroed91** [caxy/front-end-starter-kit#3]

**Comment by chris-bryant** [comment]
In my opinion, we should go with yarn. It's essentially the same workflow as npm, so there's no learning curve, it eliminates "works for me" bugs by introducing a lock file, and has the additional benefit of also searching the bower registry for packages. Even if there is some unforeseen consequence of choosing yarn, we can easily switch back to npm, since yarn still uses the exact same package.json format.

**Comment by jschroed91** [comment]
Yarn it is.
